FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN rm -rf CashFlow.Api/obj CashFlow.Api/bin
RUN dotnet nuget locals all --clear
RUN dotnet restore "CashFlow.Api/CashFlow.Api.csproj" --no-cache
RUN dotnet publish "CashFlow.Api/CashFlow.Api.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "CashFlow.Api.dll"]
