global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cashflow-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']